name: 🚀 Feature Request
description: Suggest an idea or enhancement for FORENZA
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Suggest an enhancement or new biocomputational capability for FORENZA.
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem or opportunity.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Describe your proposed enhancement or workflow.
      placeholder: Provide details...
    validations:
      required: true
