import {
  Dna,
  BarChart3,
  Brain,
  Microscope,
  Sparkles,
  ShieldCheck,
  Fingerprint,
  FlaskConical,
  Layers,
  Cpu,
  Lock,
  CheckCircle,
  Clock,
  TrendingUp,
  GitBranch,
  Binary,
  Pill,
  Eye,
  Bug,
  Syringe,
  PackageCheck,
  Scale,
  Zap,
  Database,
  Target,
  Globe,
  Mountain,
  TreePine,
  Crosshair as CrosshairIcon,
  LucideIcon,
} from "lucide-react";

export type CategoryId =
  | "genotyping"
  | "lineage"
  | "phenotyping"
  | "epigenetics"
  | "pathology"
  | "lims_governance"
  | "geoint";

export type ModuleMaturity = "ACTIVE" | "DEMO" | "PLACEHOLDER";

export interface SubsystemTab {
  id: string;
  label: string;
  shortTitle: string;
  icon: LucideIcon;
  badge: string;
  maturity: ModuleMaturity;
  maturityNote: string;
  pillarId: CategoryId;
  method: string;
  standard?: string;
}

export interface SubsystemCategory {
  id: CategoryId;
  label: string;
  shortLabel: string;
  pillarNumber: number;
  icon: LucideIcon;
  color: "cyan" | "emerald" | "purple" | "rose" | "orange" | "blue" | "teal";
  tagline: string;
  description: string;
  researchFile: string;
  tabs: SubsystemTab[];
}

export const MATURITY_CONFIG: Record<
  ModuleMaturity,
  {
    label: string;
    shortLabel: string;
    color: string;
    bg: string;
    border: string;
    dot: string;
    tagBg: string;
    tagText: string;
    tagBorder: string;
    desc: string;
  }
> = {
  ACTIVE: {
    label: "ACTIVE ENGINE",
    shortLabel: "ACTIVE",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    dot: "bg-emerald-400 animate-pulse",
    tagBg: "bg-emerald-500/20",
    tagText: "text-emerald-300",
    tagBorder: "border-emerald-500/40",
    desc: "Validated mathematical engine with live biocomputational parameters & ISO-compliant algorithms.",
  },
  DEMO: {
    label: "DEMO SIMULATOR",
    shortLabel: "DEMO",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    dot: "bg-cyan-400",
    tagBg: "bg-cyan-500/20",
    tagText: "text-cyan-300",
    tagBorder: "border-cyan-500/40",
    desc: "Interactive scientific simulation and calibrated training benchmark model.",
  },
  PLACEHOLDER: {
    label: "RESEARCH PROTOTYPE",
    shortLabel: "PROTOTYPE",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    dot: "bg-amber-400",
    tagBg: "bg-amber-500/20",
    tagText: "text-amber-300",
    tagBorder: "border-amber-500/40",
    desc: "Experimental laboratory module under active development and research roadmap.",
  },
};

export const COLOR_CLASSES: Record<
  string,
  { text: string; bg: string; border: string; activeBg: string; glow: string }
> = {
  emerald: {
    text: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    activeBg: "bg-emerald-500/15",
    glow: "shadow-[0_0_15px_rgba(16,185,129,0.2)]",
  },
  cyan: {
    text: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    activeBg: "bg-cyan-500/15",
    glow: "shadow-[0_0_15px_rgba(6,182,212,0.2)]",
  },
  purple: {
    text: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/30",
    activeBg: "bg-purple-500/15",
    glow: "shadow-[0_0_15px_rgba(168,85,247,0.2)]",
  },
  orange: {
    text: "text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/30",
    activeBg: "bg-orange-500/15",
    glow: "shadow-[0_0_15px_rgba(249,115,22,0.2)]",
  },
  blue: {
    text: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    activeBg: "bg-blue-500/15",
    glow: "shadow-[0_0_15px_rgba(59,130,246,0.2)]",
  },
  rose: {
    text: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30",
    activeBg: "bg-rose-500/15",
    glow: "shadow-[0_0_15px_rgba(244,63,94,0.2)]",
  },
  teal: {
    text: "text-teal-400",
    bg: "bg-teal-500/10",
    border: "border-teal-500/30",
    activeBg: "bg-teal-500/15",
    glow: "shadow-[0_0_15px_rgba(20,184,166,0.2)]",
  },
};

export const SUBSYSTEM_CATEGORIES: SubsystemCategory[] = [
  {
    id: "genotyping",
    label: "Probabilistic Genotyping",
    shortLabel: "Genotyping",
    pillarNumber: 1,
    icon: Cpu,
    color: "cyan",
    tagline: "Autosomal STR Likelihood Ratios & Continuous MCMC Mixture Deconvolution",
    description:
      "Continuous EuroForMix Gamma & STRmix Log-Normal mixture deconvolution, Balding-Nichols Fst coancestry, stochastic LTDNA dropout modeling, and Tippett ROC validation calibration.",
    researchFile: "pillar_1_probabilistic_genotyping_research.md",
    tabs: [
      {
        id: "str",
        label: "01. Autosomal STR Engine",
        shortTitle: "STR-24 Engine",
        icon: Binary,
        badge: "STR-24",
        maturity: "ACTIVE",
        maturityNote: "Live 24-locus Autosomal STR LR computation with Balding-Nichols / NRC-II formulas.",
        pillarId: "genotyping",
        method: "Balding-Nichols P(G|θ) & Combined ∏ LR_l",
        standard: "NRC II Rec 4.4 / SWGDAM",
      },
      {
        id: "mcmc",
        label: "02. MCMC Mixture Deconv.",
        shortTitle: "MCMC Deconvolution",
        icon: Layers,
        badge: "MCMC-MH",
        maturity: "ACTIVE",
        maturityNote: "Live Metropolis-Hastings 3-contributor MCMC mixture deconvolution iteration engine.",
        pillarId: "genotyping",
        method: "Metropolis-Hastings Continuous Gamma Likelihood",
        standard: "EuroForMix / STRmix Protocol",
      },
      {
        id: "population",
        label: "03. Dirichlet Fst Population",
        shortTitle: "Dirichlet Fst",
        icon: BarChart3,
        badge: "NRC-II",
        maturity: "ACTIVE",
        maturityNote: "Live Bayesian theta coancestry shift calculator across subpopulation priors.",
        pillarId: "genotyping",
        method: "Wright Fst & Dirichlet Multinomial Posterior",
        standard: "NIST 1036 / NRC II Rec 4.10",
      },
      {
        id: "touch",
        label: "04. Touch DNA & LTDNA",
        shortTitle: "Touch & LTDNA",
        icon: Fingerprint,
        badge: "LTDNA",
        maturity: "DEMO",
        maturityNote: "Interactive low-template drop-out & stochastic stutter simulation model.",
        pillarId: "genotyping",
        method: "Gill Logistic P(D) & Drop-in Poisson Kinetics",
        standard: "ISFG Touch DNA Guidelines",
      },
      {
        id: "validation",
        label: "05. Tippett Calibration Lab",
        shortTitle: "Tippett Calibration",
        icon: CheckCircle,
        badge: "TIPPETT",
        maturity: "DEMO",
        maturityNote: "Empirical Tippett and ROC validation curve simulator for laboratory accreditation.",
        pillarId: "genotyping",
        method: "Tippett Cumulative Empirical Log10(LR) Curves",
        standard: "ENFSI 2017 / ISO 17025 §7.2",
      },
    ],
  },
  {
    id: "lineage",
    label: "Lineage Forensics & Kinship",
    shortLabel: "Lineage & Kinship",
    pillarNumber: 2,
    icon: Dna,
    color: "emerald",
    tagline: "Uniparental Y/mtDNA Lineages, Linkage Disequilibrium & Disaster Victim ID",
    description:
      "Y-FILER Plus 27-loci Clopper-Pearson 95% upper bounds, Argus X-12 clustered linkage kinship index, EMPOP mitochondrial rCRS alignment, and Interpol DVI joint likelihood solvers.",
    researchFile: "pillar_2_lineage_kinship_research.md",
    tabs: [
      {
        id: "lineage_y",
        label: "06. Y-STR Haplotypes",
        shortTitle: "Y-STR Haplotypes",
        icon: Dna,
        badge: "Y-STR",
        maturity: "ACTIVE",
        maturityNote: "Live Y-chromosomal paternal haplotype matching & discrete allele counter.",
        pillarId: "lineage",
        method: "YHRD Frequency & Clopper-Pearson 95% Exact Bound",
        standard: "Y-FILER Plus 27-Loci",
      },
      {
        id: "lineage_x",
        label: "07. X-STR Linkage & KI",
        shortTitle: "X-STR Linkage",
        icon: GitBranch,
        badge: "X-STR",
        maturity: "DEMO",
        maturityNote: "Interactive X-chromosomal kinship index & pedigree relationship traversal.",
        pillarId: "lineage",
        method: "Pairwise Haplotype Sharing (PHS) & Linkage Decoupling",
        standard: "Argus X-12 Kinship Protocol",
      },
      {
        id: "lineage_mt",
        label: "08. mtDNA rCRS Alignment",
        shortTitle: "mtDNA rCRS",
        icon: TrendingUp,
        badge: "mtDNA",
        maturity: "ACTIVE",
        maturityNote: "Live mitochondrial rCRS variant aligner & haplogroup mapper.",
        pillarId: "lineage",
        method: "EMPOP rCRS / RSRS Pairwise Needleman-Wunsch",
        standard: "EMPOP & ISFG mtDNA",
      },
      {
        id: "dvi",
        label: "09. DVI Mass Disaster",
        shortTitle: "DVI Reconciliation",
        icon: Database,
        badge: "DVI-PED",
        maturity: "DEMO",
        maturityNote: "Disaster Victim Identification ante/post-mortem reconciliation simulator.",
        pillarId: "lineage",
        method: "Ante/Post-Mortem Joint Multilocus LR Reconciliation",
        standard: "Interpol DVI Standards",
      },
      {
        id: "humanid",
        label: "10. Ancient DNA & SNP Mapper",
        shortTitle: "aDNA SNP Mapper",
        icon: Fingerprint,
        badge: "aDNA-SNP",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for ancient DNA post-mortem damage pattern modeling.",
        pillarId: "lineage",
        method: "Briggs MapDamage C->T Deamination Kinetics",
        standard: "Paleogenomics aDNA Protocol",
      },
    ],
  },
  {
    id: "phenotyping",
    label: "Phenotyping & Ancestry",
    shortLabel: "Phenotype & BGA",
    pillarNumber: 3,
    icon: Eye,
    color: "purple",
    tagline: "Externally Visible Characteristics (EVCs) & 55-SNP AIM Biogeographic Centroids",
    description:
      "HIrisPlex-S 41-SNP multinomial logistic regression with MC1R epistasis, 55-SNP AIM continental centroid WGS84 geodesic projections, and 3D craniofacial morphology reconstruction.",
    researchFile: "pillar_3_phenotype_ancestry_research.md",
    tabs: [
      {
        id: "hirisplex",
        label: "11. HIrisPlex-S Pigmentation",
        shortTitle: "HIrisPlex-S 41-SNP",
        icon: Eye,
        badge: "HIRISPLEX",
        maturity: "ACTIVE",
        maturityNote: "Live Walsh et al. (2018) multinomial logistic regression engine with 6-SNP mutation lab.",
        pillarId: "phenotyping",
        method: "Multinomial Logistic Regression Softmax Sum-to-One",
        standard: "Walsh et al. (2018) / VISAGE",
      },
      {
        id: "ancestry",
        label: "12. Biogeographic Ancestry (BGA)",
        shortTitle: "55-SNP AIM BGA",
        icon: TrendingUp,
        badge: "BGA-55",
        maturity: "ACTIVE",
        maturityNote: "Live 55-SNP AIM continental centroid projection & population admixture estimator.",
        pillarId: "phenotyping",
        method: "Kidd 55-SNP Continental Centroid GIS Projection",
        standard: "ISFG ForenSeq BGA",
      },
      {
        id: "craniofacial",
        label: "13. Facial & Craniofacial 3D",
        shortTitle: "3D Craniofacial",
        icon: Brain,
        badge: "CRANIO-3D",
        maturity: "DEMO",
        maturityNote: "Interactive 3D facial morphology phenotype reconstruction simulator.",
        pillarId: "phenotyping",
        method: "Claes Craniofacial Mesh Morphometry Predictor",
        standard: "3D Anthropometric Norms",
      },
      {
        id: "hair",
        label: "14. Hair Texture & Balding",
        shortTitle: "Hair & Balding",
        icon: Sparkles,
        badge: "HAIR-TEX",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for hair fiber morphology and androgenetic alopecia mapping.",
        pillarId: "phenotyping",
        method: "Polygenic Risk Score (PRS) Follicle Regression",
        standard: "VISAGE EVC Panel",
      },
      {
        id: "freckling",
        label: "15. Freckling & UV Sensitivity",
        shortTitle: "MC1R Epistasis",
        icon: Eye,
        badge: "MC1R-UV",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for MC1R epistatic variant UV sensitivity modeling.",
        pillarId: "phenotyping",
        method: "MC1R Epistatic Variant Loss-of-Function Modifier",
        standard: "Epistatic Penetrance Scale",
      },
    ],
  },
  {
    id: "epigenetics",
    label: "Epigenetics & Aging",
    shortLabel: "Epigenetics & Age",
    pillarNumber: 4,
    icon: Clock,
    color: "rose",
    tagline: "DNA Methylation Chronometers, tDMR Tissue Deconvolution & Lifestyle Biomarkers",
    description:
      "Horvath & VISAGE multi-tissue elastic net epigenetic age clocks (y0=20.0), tDMR 6-tissue source origin deconvolution (QDA/NNLS), lifestyle AHRR pack-years, and telomere length decay.",
    researchFile: "pillar_4_epigenetics_aging_research.md",
    tabs: [
      {
        id: "age",
        label: "16. Horvath Epigenetic Clock",
        shortTitle: "Horvath Clock",
        icon: Clock,
        badge: "HORVATH",
        maturity: "ACTIVE",
        maturityNote: "Live Horvath 5-CpG methylation age estimation engine with live delta.",
        pillarId: "epigenetics",
        method: "Piecewise Elastic Net Anti-Logit Transformation (y0=20.0)",
        standard: "Horvath (2013) / VISAGE Age",
      },
      {
        id: "bodyfluid",
        label: "17. Body Fluid tDMR Origin",
        shortTitle: "tDMR Body Fluid",
        icon: Syringe,
        badge: "tDMR-FLUID",
        maturity: "DEMO",
        maturityNote: "Tissue-specific differential methylation body fluid classification simulator.",
        pillarId: "epigenetics",
        method: "Non-Negative Least Squares (NNLS) / QDA 6-Tissue Deconv",
        standard: "VISAGE Body Fluid Matrix",
      },
      {
        id: "lifestyle",
        label: "18. Lifestyle Epigenetics AHRR",
        shortTitle: "Lifestyle AHRR",
        icon: Zap,
        badge: "AHRR",
        maturity: "DEMO",
        maturityNote: "AHRR environmental smoking & lifestyle epigenetic biomarker analyzer.",
        pillarId: "epigenetics",
        method: "AHRR cg05575921 Hypomethylation Pack-Years Regression",
        standard: "Lifestyle Epigenetics Norm",
      },
      {
        id: "telomere",
        label: "19. Telomere Chronometer",
        shortTitle: "Telomere Decay",
        icon: Clock,
        badge: "TELO-CHRONO",
        maturity: "DEMO",
        maturityNote: "Telomere length biological chronometer decay simulator.",
        pillarId: "epigenetics",
        method: "qPCR T/S Ratio Log-Linear Decay Chronometer",
        standard: "Telomeric Biological Aging",
      },
      {
        id: "mirna",
        label: "20. Forensic MicroRNA Profiling",
        shortTitle: "MicroRNA Profiling",
        icon: FlaskConical,
        badge: "miRNA",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for organ-specific microRNA differential expression.",
        pillarId: "epigenetics",
        method: "Delta-Delta Ct Normalized Biomarker Classification",
        standard: "Forensic miRNA Consortium",
      },
    ],
  },
  {
    id: "pathology",
    label: "Physical Evidence & Trace",
    shortLabel: "Physical Trace",
    pillarNumber: 5,
    icon: Microscope,
    color: "orange",
    tagline: "3D BPA Least-Squares, SEM-EDX GSR Ballistics, Thermal PMI & Toxicokinetics",
    description:
      "3D Bloodstain Pattern Analysis (BPA) trigonometric area of origin optimization, ASTM E1588 SEM-EDX GSR ternary classifier, Calliphoridae thermal summation (ADD/ADH), and post-mortem PMR toxicokinetics.",
    researchFile: "pillar_5_physical_evidence_research.md",
    tabs: [
      {
        id: "bpa",
        label: "21. Bloodstain Pattern (BPA 3D)",
        shortTitle: "3D BPA Origin",
        icon: Eye,
        badge: "BPA-3D",
        maturity: "ACTIVE",
        maturityNote: "Live 3D trigonometric area of origin & impact angle calculator.",
        pillarId: "pathology",
        method: "3D Directional Ray Intersection & Least-Squares Origin",
        standard: "MacDonell (1979) / ASB Standard 033",
      },
      {
        id: "microscopy",
        label: "22. Ballistics & SEM-EDX GSR",
        shortTitle: "SEM-EDX & Ballistics",
        icon: Target,
        badge: "GSR-CMC",
        maturity: "ACTIVE",
        maturityNote: "Live ASTM E1588-20 SEM-EDX GSR analysis & 3D CMC firearm striation matching.",
        pillarId: "pathology",
        method: "Pb-Ba-Sb Ternary Characteristic Particle Classifier",
        standard: "ASTM E1588-20 / NIST CMC",
      },
      {
        id: "botany",
        label: "23. Forensic Entomology & PMI",
        shortTitle: "Entomology (ADD/ADH)",
        icon: Bug,
        badge: "ENTO-PMI",
        maturity: "ACTIVE",
        maturityNote: "Live Calliphoridae thermal summation (ADD/ADH) & minimum PMI solver.",
        pillarId: "pathology",
        method: "Thermal Summation K = y * (T - T0) ADD/ADH Integration",
        standard: "European Association for Forensic Entomology",
      },
      {
        id: "toxicology",
        label: "24. Trace Spectroscopy & MSI",
        shortTitle: "MSI & ATR-FTIR",
        icon: Sparkles,
        badge: "MSI-FTIR",
        maturity: "ACTIVE",
        maturityNote: "Live multispectral imaging (365-850nm) & ATR-FTIR / Raman Hit Quality Index matching.",
        pillarId: "pathology",
        method: "Vector Euclidean Dot Product Hit Quality Index (HQI)",
        standard: "ASTM E2224 / SWGMAT",
      },
      {
        id: "serology",
        label: "25. Post-Mortem Toxicokinetics",
        shortTitle: "PMR Toxicokinetics",
        icon: Pill,
        badge: "TOX-PMR",
        maturity: "ACTIVE",
        maturityNote: "Live post-mortem drug redistribution (PMR C/P ratios) & Widmark back-extrapolation.",
        pillarId: "pathology",
        method: "Central/Peripheral (C/P) Ratio & Widmark Back-Extrapolation",
        standard: "SOFT / AAFS Toxicokinetics",
      },
    ],
  },
  {
    id: "lims_governance",
    label: "Governance, LIMS & ZKP",
    shortLabel: "Governance & ZKP",
    pillarNumber: 6,
    icon: ShieldCheck,
    color: "blue",
    tagline: "Cryptographic Binary Merkle Trees, Circom BN254 ZKP & ISO 17025 Uncertainty",
    description:
      "Binary Merkle tree chain of custody with O(log2 N) inclusion proofs, Circom Groth16 blind forensic auditor on BN254 pairings, ISO/IEC 17025:2017 GUM expanded uncertainty, and ENFSI 7-tier verbal scale.",
    researchFile: "pillar_6_lims_zkp_reporting_research.md",
    tabs: [
      {
        id: "lims",
        label: "26. Merkle Custody Ledger",
        shortTitle: "Merkle Custody",
        icon: PackageCheck,
        badge: "MERKLE-COC",
        maturity: "ACTIVE",
        maturityNote: "Live cryptographic binary Merkle tree chain of custody & O(log2 N) proof generator.",
        pillarId: "lims_governance",
        method: "Binary Merkle Tree O(log2 N) Leaf Inclusion Proofs",
        standard: "ISO/IEC 17025 §7.8.2 / NIST SP 800-147",
      },
      {
        id: "zkp",
        label: "27. ZKP Blind Forensic Auditor",
        shortTitle: "Circom ZKP Auditor",
        icon: Lock,
        badge: "ZKP-BN254",
        maturity: "ACTIVE",
        maturityNote: "Live Circom BN254 Groth16 zero-knowledge proof generation & bilinear multi-pairing verification.",
        pillarId: "lims_governance",
        method: "Groth16 Zero-Knowledge SNARK Witness Verification",
        standard: "Circom 2.1 / BN254 Curve",
      },
      {
        id: "qc",
        label: "28. ISO 17025 QA/QC Matrix",
        shortTitle: "ISO QA/QC Matrix",
        icon: ShieldCheck,
        badge: "ISO-17025",
        maturity: "ACTIVE",
        maturityNote: "Live ISO 17025 validation checklist & standard operating procedure validator.",
        pillarId: "lims_governance",
        method: "GUM Expanded Uncertainty U95% = 2.00 * u_c",
        standard: "ISO/IEC 17025:2017 / GUM JCGM 100",
      },
      {
        id: "court",
        label: "29. Expert Witness Court Mode",
        shortTitle: "Expert Court Mode",
        icon: Scale,
        badge: "COURT-MODE",
        maturity: "DEMO",
        maturityNote: "Interactive expert witness courtroom reporting & ENFSI verbal predicate synthesizer.",
        pillarId: "lims_governance",
        method: "ENFSI (2017) 7-Tier Standardized Verbal Predicates",
        standard: "ENFSI Guideline / Daubert Standard",
      },
      {
        id: "evidenceos",
        label: "30. 3D Spatial Juror Visualizer",
        shortTitle: "3D Juror Visualizer",
        icon: Layers,
        badge: "JUROR-3D",
        maturity: "DEMO",
        maturityNote: "3D spatial crime scene reconstruction & interactive juror visualizer engine.",
        pillarId: "lims_governance",
        method: "Spatial 3D Photogrammetry & Trajectory Overlay",
        standard: "Courtroom Demonstrative Evidence",
      },
    ],
  },
  {
    id: "geoint",
    label: "Geo-Forensic Intelligence",
    shortLabel: "Geo-Intelligence",
    pillarNumber: 7,
    icon: Globe,
    color: "teal",
    tagline: "Multi-Isotope Isoscapes, Forensic Pedology CoDa & Rossmo Spatial Profiling",
    description:
      "Multi-isotope H/O/Sr spatial isoscapes, QXRD Rietveld soil pedology compositional data analysis (CoDa), palynology Relative Pollen Frequency (RPF), and Rossmo geographic hunting surfaces.",
    researchFile: "pillar_7_geo_forensics_research.md",
    tabs: [
      {
        id: "geo_isoscape",
        label: "31. Multi-Isotope Isoscape Engine",
        shortTitle: "Isoscape Isotope",
        icon: Globe,
        badge: "ISOTOPE",
        maturity: "ACTIVE",
        maturityNote: "Live multi-isotope spatial isoscape mapping (H/O/Sr) & Bayesian centroid resolution.",
        pillarId: "geoint",
        method: "Spatial Multi-Isotope Bayesian Surface Likelihood Integration",
        standard: "IAEA GNIP / Bowen Isoscape",
      },
      {
        id: "geo_soil",
        label: "32. Forensic Soil Pedology & CoDa",
        shortTitle: "Soil Pedology CoDa",
        icon: Mountain,
        badge: "SOIL-CODA",
        maturity: "ACTIVE",
        maturityNote: "Live QXRD Rietveld mineralogy, ZTR index & ASTM E3272-21 Hotelling T2 comparison.",
        pillarId: "geoint",
        method: "Centered Log-Ratio (clr) & Hotelling T2 Multivariate Distance",
        standard: "ASTM E3272-21 Forensic Soil",
      },
      {
        id: "geo_palynology",
        label: "33. Palynology & eDNA Metagenomics",
        shortTitle: "Palynology & eDNA",
        icon: TreePine,
        badge: "PALYNO",
        maturity: "ACTIVE",
        maturityNote: "Live Relative Pollen Frequency (RPF), 6-biome classifier & 16S/ITS spatial regression.",
        pillarId: "geoint",
        method: "Relative Pollen Frequency (RPF) & 16S/ITS OTU Regression",
        standard: "Forensic Palynology Protocols",
      },
      {
        id: "geo_rossmo",
        label: "34. Rossmo Geographic Profiling",
        shortTitle: "Rossmo Profiling",
        icon: CrosshairIcon,
        badge: "ROSSMO",
        maturity: "ACTIVE",
        maturityNote: "Live Rossmo targeted hunting probability surface & Canter circle Marauder classification.",
        pillarId: "geoint",
        method: "Rossmo Distance-Decayed Targeted Hunting Probability Surface",
        standard: "Rossmo Formula / ECRI Standards",
      },
      {
        id: "geo_fusion",
        label: "35. Multi-Criteria Bayesian GIS Fusion",
        shortTitle: "Bayesian GIS Fusion",
        icon: Layers,
        badge: "FUSION",
        maturity: "ACTIVE",
        maturityNote: "Live multi-criteria Bayesian raster integration, 2D adaptive KDE & ENFSI report generator.",
        pillarId: "geoint",
        method: "Spatial Log-Likelihood Raster Product Fusion & 2D Adaptive KDE",
        standard: "ENFSI Spatial Guideline",
      },
    ],
  },
];

export const ALL_SUBSYSTEM_TABS: SubsystemTab[] = SUBSYSTEM_CATEGORIES.flatMap((c) => c.tabs);

export function getSubsystemCategory(id: CategoryId | string): SubsystemCategory | undefined {
  return SUBSYSTEM_CATEGORIES.find((c) => c.id === id);
}

export function getSubsystemTab(id: string): SubsystemTab | undefined {
  return ALL_SUBSYSTEM_TABS.find((t) => t.id === id);
}
