import {
  Dna,
  BarChart3,
  Brain,
  Microscope,
  Sparkles,
  ShieldCheck,
  Fingerprint,
  FlaskConical,
  Layers,
  Cpu,
  Lock,
  CheckCircle,
  Clock,
  TrendingUp,
  GitBranch,
  Binary,
  Pill,
  Eye,
  Bug,
  Syringe,
  PackageCheck,
  Scale,
  Zap,
  Database,
  Target,
  Globe,
  Mountain,
  TreePine,
  Crosshair as CrosshairIcon,
  LucideIcon,
} from "lucide-react";

export type CategoryId =
  | "genotyping"
  | "lineage"
  | "phenotyping"
  | "epigenetics"
  | "pathology"
  | "lims_governance"
  | "geoint";

export type ModuleMaturity = "ACTIVE" | "DEMO" | "PLACEHOLDER";

export interface SubsystemTab {
  id: string;
  label: string;
  labelTr?: string;
  shortTitle: string;
  shortTitleTr?: string;
  icon: LucideIcon;
  badge: string;
  maturity: ModuleMaturity;
  maturityNote: string;
  maturityNoteTr?: string;
  pillarId: CategoryId;
  method: string;
  methodTr?: string;
  standard?: string;
  standardTr?: string;
}

export interface SubsystemCategory {
  id: CategoryId;
  label: string;
  labelTr?: string;
  shortLabel: string;
  shortLabelTr?: string;
  pillarNumber: number;
  icon: LucideIcon;
  color: "cyan" | "emerald" | "purple" | "rose" | "orange" | "blue" | "teal";
  tagline: string;
  taglineTr?: string;
  description: string;
  descriptionTr?: string;
  researchFile: string;
  tabs: SubsystemTab[];
}

export const MATURITY_CONFIG: Record<
  ModuleMaturity,
  {
    label: string;
    shortLabel: string;
    color: string;
    bg: string;
    border: string;
    dot: string;
    tagBg: string;
    tagText: string;
    tagBorder: string;
    desc: string;
  }
> = {
  ACTIVE: {
    label: "ACTIVE ENGINE",
    shortLabel: "ACTIVE",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    dot: "bg-emerald-400 animate-pulse",
    tagBg: "bg-emerald-500/20",
    tagText: "text-emerald-300",
    tagBorder: "border-emerald-500/40",
    desc: "Validated mathematical engine with live biocomputational parameters & ISO-compliant algorithms.",
  },
  DEMO: {
    label: "DEMO SIMULATOR",
    shortLabel: "DEMO",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    dot: "bg-cyan-400",
    tagBg: "bg-cyan-500/20",
    tagText: "text-cyan-300",
    tagBorder: "border-cyan-500/40",
    desc: "Interactive scientific simulation and calibrated training benchmark model.",
  },
  PLACEHOLDER: {
    label: "RESEARCH PROTOTYPE",
    shortLabel: "PROTOTYPE",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    dot: "bg-amber-400",
    tagBg: "bg-amber-500/20",
    tagText: "text-amber-300",
    tagBorder: "border-amber-500/40",
    desc: "Experimental laboratory module under active development and research roadmap.",
  },
};

export const COLOR_CLASSES: Record<
  string,
  { text: string; bg: string; border: string; activeBg: string; glow: string }
> = {
  emerald: {
    text: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    activeBg: "bg-emerald-500/15",
    glow: "shadow-[0_0_15px_rgba(16,185,129,0.2)]",
  },
  cyan: {
    text: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    activeBg: "bg-cyan-500/15",
    glow: "shadow-[0_0_15px_rgba(6,182,212,0.2)]",
  },
  purple: {
    text: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/30",
    activeBg: "bg-purple-500/15",
    glow: "shadow-[0_0_15px_rgba(168,85,247,0.2)]",
  },
  orange: {
    text: "text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/30",
    activeBg: "bg-orange-500/15",
    glow: "shadow-[0_0_15px_rgba(249,115,22,0.2)]",
  },
  blue: {
    text: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    activeBg: "bg-blue-500/15",
    glow: "shadow-[0_0_15px_rgba(59,130,246,0.2)]",
  },
  rose: {
    text: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30",
    activeBg: "bg-rose-500/15",
    glow: "shadow-[0_0_15px_rgba(244,63,94,0.2)]",
  },
  teal: {
    text: "text-teal-400",
    bg: "bg-teal-500/10",
    border: "border-teal-500/30",
    activeBg: "bg-teal-500/15",
    glow: "shadow-[0_0_15px_rgba(20,184,166,0.2)]",
  },
};

export const SUBSYSTEM_CATEGORIES: SubsystemCategory[] = [
  {
    id: "genotyping",
    label: "Probabilistic Genotyping",
    labelTr: "Olasılıksal Genotipleme",
    shortLabel: "Genotyping",
    shortLabelTr: "Genotipleme",
    pillarNumber: 1,
    icon: Cpu,
    color: "cyan",
    tagline: "Autosomal STR Likelihood Ratios & Continuous MCMC Mixture Deconvolution",
    taglineTr: "Otozomal STR Olasılık Oranları & Sürekli MCMC Karışım Dekonvolüsyonu",
    description:
      "Continuous EuroForMix Gamma & STRmix Log-Normal mixture deconvolution, Balding-Nichols Fst coancestry, stochastic LTDNA dropout modeling, and Tippett ROC validation calibration.",
    descriptionTr:
      "Sürekli EuroForMix Gama & STRmix Log-Normal karışım dekonvolüsyonu, Balding-Nichols Fst akrabalık düzeltmesi, stokastik LTDNA alel kaybı modellemesi ve Tippett ROC doğrulama kalibrasyonu.",
    researchFile: "pillar_1_probabilistic_genotyping_research.md",
    tabs: [
      {
        id: "str",
        label: "01. Autosomal STR Engine",
        labelTr: "01. Otozomal STR Motoru",
        shortTitle: "STR-24 Engine",
        shortTitleTr: "STR-24 Motoru",
        icon: Binary,
        badge: "STR-24",
        maturity: "ACTIVE",
        maturityNote: "Live 24-locus Autosomal STR LR computation with Balding-Nichols / NRC-II formulas.",
        maturityNoteTr: "Balding-Nichols / NRC-II formülleri ile canlı 24 lokuslu Otozomal STR LR hesaplaması.",
        pillarId: "genotyping",
        method: "Balding-Nichols P(G|θ) & Combined ∏ LR_l",
        methodTr: "Balding-Nichols P(G|θ) & Birleşik ∏ LR_l",
        standard: "NRC II Rec 4.4 / SWGDAM",
        standardTr: "NRC II Tavsiye 4.4 / SWGDAM",
      },
      {
        id: "mcmc",
        label: "02. MCMC Mixture Deconv.",
        labelTr: "02. MCMC Karışım Dekonvolüsyonu",
        shortTitle: "MCMC Deconvolution",
        shortTitleTr: "MCMC Dekonvolüsyon",
        icon: Layers,
        badge: "MCMC-MH",
        maturity: "ACTIVE",
        maturityNote: "Live Metropolis-Hastings 3-contributor MCMC mixture deconvolution iteration engine.",
        maturityNoteTr: "3 katkılı Metropolis-Hastings MCMC karışım dekonvolüsyon yineleme motoru.",
        pillarId: "genotyping",
        method: "Metropolis-Hastings Continuous Gamma Likelihood",
        methodTr: "Metropolis-Hastings Sürekli Gama Olabilirlik Modeli",
        standard: "EuroForMix / STRmix Protocol",
        standardTr: "EuroForMix / STRmix Protokolü",
      },
      {
        id: "population",
        label: "03. Dirichlet Fst Population",
        labelTr: "03. Dirichlet Fst Popülasyonu",
        shortTitle: "Dirichlet Fst",
        shortTitleTr: "Dirichlet Fst",
        icon: BarChart3,
        badge: "NRC-II",
        maturity: "ACTIVE",
        maturityNote: "Live Bayesian theta coancestry shift calculator across subpopulation priors.",
        maturityNoteTr: "Alt popülasyon öncülleri üzerinden canlı Bayesyen teta akrabalık sapma hesaplayıcısı.",
        pillarId: "genotyping",
        method: "Wright Fst & Dirichlet Multinomial Posterior",
        methodTr: "Wright Fst & Dirichlet Çok Terimli Sonsal Dağılım",
        standard: "NIST 1036 / NRC II Rec 4.10",
        standardTr: "NIST 1036 / NRC II Tavsiye 4.10",
      },
      {
        id: "touch",
        label: "04. Touch DNA & LTDNA",
        labelTr: "04. Temas DNA & LTDNA",
        shortTitle: "Touch & LTDNA",
        shortTitleTr: "Temas & LTDNA",
        icon: Fingerprint,
        badge: "LTDNA",
        maturity: "DEMO",
        maturityNote: "Interactive low-template drop-out & stochastic stutter simulation model.",
        maturityNoteTr: "Düşük şablonlu alel kaybı (dropout) & stokastik kekeleme simülasyon modeli.",
        pillarId: "genotyping",
        method: "Gill Logistic P(D) & Drop-in Poisson Kinetics",
        methodTr: "Gill Lojistik P(D) & Kontaminasyon Poisson Kinetiği",
        standard: "ISFG Touch DNA Guidelines",
        standardTr: "ISFG Temas DNA Kılavuzları",
      },
      {
        id: "validation",
        label: "05. Tippett Calibration Lab",
        labelTr: "05. Tippett Kalibrasyon Laboratuvarı",
        shortTitle: "Tippett Calibration",
        shortTitleTr: "Tippett Kalibrasyonu",
        icon: CheckCircle,
        badge: "TIPPETT",
        maturity: "DEMO",
        maturityNote: "Empirical Tippett and ROC validation curve simulator for laboratory accreditation.",
        maturityNoteTr: "Laboratuvar akreditasyonu için ampirik Tippett ve ROC doğrulama eğrisi simülatörü.",
        pillarId: "genotyping",
        method: "Tippett Cumulative Empirical Log10(LR) Curves",
        methodTr: "Tippett Kümülatif Ampirik Log10(LR) Eğrileri",
        standard: "ENFSI 2017 / ISO 17025 §7.2",
        standardTr: "ENFSI 2017 / ISO 17025 Madde 7.2",
      },
    ],
  },
  {
    id: "lineage",
    label: "Lineage Forensics & Kinship",
    labelTr: "Soy Forensiği & Akrabalık",
    shortLabel: "Lineage & Kinship",
    shortLabelTr: "Soy & Akrabalık",
    pillarNumber: 2,
    icon: Dna,
    color: "emerald",
    tagline: "Uniparental Y/mtDNA Lineages, Linkage Disequilibrium & Disaster Victim ID",
    taglineTr: "Tek Ebeveynli Y/mtDNA Soy Hatları, Bağlantı Dengesizliği & DVI Kimliklendirme",
    description:
      "Y-FILER Plus 27-loci Clopper-Pearson 95% upper bounds, Argus X-12 clustered linkage kinship index, EMPOP mitochondrial rCRS alignment, and Interpol DVI joint likelihood solvers.",
    descriptionTr:
      "Y-FILER Plus 27 lokus Clopper-Pearson %95 üst sınırları, Argus X-12 kümelenmiş bağlantı akrabalık indeksi, EMPOP mitokondriyal rCRS hizalaması ve Interpol DVI birleşik olabilirlik çözücüleri.",
    researchFile: "pillar_2_lineage_kinship_research.md",
    tabs: [
      {
        id: "lineage_y",
        label: "06. Y-STR Haplotypes",
        labelTr: "06. Y-STR Haplotipleri",
        shortTitle: "Y-STR Haplotypes",
        shortTitleTr: "Y-STR Haplotipleri",
        icon: Dna,
        badge: "Y-STR",
        maturity: "ACTIVE",
        maturityNote: "Live Y-chromosomal paternal haplotype matching & discrete allele counter.",
        maturityNoteTr: "Canlı Y-kromozomal babasoylu haplotip eşleştirme & ayrık alel sayacı.",
        pillarId: "lineage",
        method: "YHRD Frequency & Clopper-Pearson 95% Exact Bound",
        methodTr: "YHRD Frekansı & Clopper-Pearson %95 Kesin Güven Sınırı",
        standard: "Y-FILER Plus 27-Loci",
        standardTr: "Y-FILER Plus 27 Lokus",
      },
      {
        id: "lineage_x",
        label: "07. X-STR Linkage & KI",
        labelTr: "07. X-STR Bağlantısı & Akrabalık",
        shortTitle: "X-STR Linkage",
        shortTitleTr: "X-STR Bağlantısı",
        icon: GitBranch,
        badge: "X-STR",
        maturity: "DEMO",
        maturityNote: "Interactive X-chromosomal kinship index & pedigree relationship traversal.",
        maturityNoteTr: "Etkileşimli X-kromozomal akrabalık indeksi & soy ağacı ilişki çözümlemesi.",
        pillarId: "lineage",
        method: "Pairwise Haplotype Sharing (PHS) & Linkage Decoupling",
        methodTr: "İkili Haplotip Paylaşımı (PHS) & Bağlantı Ayrışımı",
        standard: "Argus X-12 Kinship Protocol",
        standardTr: "Argus X-12 Akrabalık Protokolü",
      },
      {
        id: "lineage_mt",
        label: "08. mtDNA rCRS Alignment",
        labelTr: "08. mtDNA rCRS Hizalaması",
        shortTitle: "mtDNA rCRS",
        shortTitleTr: "mtDNA rCRS",
        icon: TrendingUp,
        badge: "mtDNA",
        maturity: "ACTIVE",
        maturityNote: "Live mitochondrial rCRS variant aligner & haplogroup mapper.",
        maturityNoteTr: "Canlı mitokondriyal rCRS varyant hizalayıcısı & haplogrup eşleyicisi.",
        pillarId: "lineage",
        method: "EMPOP rCRS / RSRS Pairwise Needleman-Wunsch",
        methodTr: "EMPOP rCRS / RSRS İkili Needleman-Wunsch",
        standard: "EMPOP & ISFG mtDNA",
        standardTr: "EMPOP & ISFG mtDNA Standartları",
      },
      {
        id: "dvi",
        label: "09. DVI Mass Disaster",
        labelTr: "09. DVI Toplu Felaket Kimliklendirme",
        shortTitle: "DVI Reconciliation",
        shortTitleTr: "DVI Uzlaştırması",
        icon: Database,
        badge: "DVI-PED",
        maturity: "DEMO",
        maturityNote: "Disaster Victim Identification ante/post-mortem reconciliation simulator.",
        maturityNoteTr: "Felaket Kurbanı Kimliklendirme (DVI) ante/post-mortem uzlaştırma simülatörü.",
        pillarId: "lineage",
        method: "Ante/Post-Mortem Joint Multilocus LR Reconciliation",
        methodTr: "Ante/Post-Mortem Birleşik Çok Lokuslu LR Uzlaştırması",
        standard: "Interpol DVI Standards",
        standardTr: "Interpol DVI Standartları",
      },
      {
        id: "humanid",
        label: "10. Ancient DNA & SNP Mapper",
        labelTr: "10. Antik DNA & SNP Eşleyici",
        shortTitle: "aDNA SNP Mapper",
        shortTitleTr: "aDNA SNP Eşleyici",
        icon: Fingerprint,
        badge: "aDNA-SNP",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for ancient DNA post-mortem damage pattern modeling.",
        maturityNoteTr: "Antik DNA ölüm sonrası hasar örüntüsü modellemesi için araştırma prototipi.",
        pillarId: "lineage",
        method: "Briggs MapDamage C->T Deamination Kinetics",
        methodTr: "Briggs MapDamage C->T Deaminasyon Kinetiği",
        standard: "Paleogenomics aDNA Protocol",
        standardTr: "Paleogenomik aDNA Protokolü",
      },
    ],
  },
  {
    id: "phenotyping",
    label: "Phenotyping & Ancestry",
    labelTr: "Fenotipleme & Biyocoğrafi Köken",
    shortLabel: "Phenotype & BGA",
    shortLabelTr: "Fenotip & BGA",
    pillarNumber: 3,
    icon: Eye,
    color: "purple",
    tagline: "Externally Visible Characteristics (EVCs) & 55-SNP AIM Biogeographic Centroids",
    taglineTr: "Dış Görünüş Özellikleri (EVC) & 55-SNP AIM Biyocoğrafi Sentroidler",
    description:
      "HIrisPlex-S 41-SNP multinomial logistic regression with MC1R epistasis, 55-SNP AIM continental centroid WGS84 geodesic projections, and 3D craniofacial morphology reconstruction.",
    descriptionTr:
      "MC1R epistazlı HIrisPlex-S 41-SNP çok terimli lojistik regresyonu, 55-SNP AIM kıtasal sentroid WGS84 jeodezik projeksiyonları ve 3D kraniyofasiyal morfoloji rekonstrüksiyonu.",
    researchFile: "pillar_3_phenotype_ancestry_research.md",
    tabs: [
      {
        id: "hirisplex",
        label: "11. HIrisPlex-S Pigmentation",
        labelTr: "11. HIrisPlex-S Pigmentasyon Tahmini",
        shortTitle: "HIrisPlex-S 41-SNP",
        shortTitleTr: "HIrisPlex-S 41-SNP",
        icon: Eye,
        badge: "HIRISPLEX",
        maturity: "ACTIVE",
        maturityNote: "Live Walsh et al. (2018) multinomial logistic regression engine with 6-SNP mutation lab.",
        maturityNoteTr: "6-SNP mutasyon laboratuvarı ile canlı Walsh vd. (2018) çok terimli lojistik regresyon motoru.",
        pillarId: "phenotyping",
        method: "Multinomial Logistic Regression Softmax Sum-to-One",
        methodTr: "Çok Terimli Lojistik Regresyon Softmax Toplamı-Bire Eşit",
        standard: "Walsh et al. (2018) / VISAGE",
        standardTr: "Walsh vd. (2018) / VISAGE",
      },
      {
        id: "ancestry",
        label: "12. Biogeographic Ancestry (BGA)",
        labelTr: "12. Biyocoğrafi Köken (BGA)",
        shortTitle: "55-SNP AIM BGA",
        shortTitleTr: "55-SNP AIM BGA",
        icon: TrendingUp,
        badge: "BGA-55",
        maturity: "ACTIVE",
        maturityNote: "Live 55-SNP AIM continental centroid projection & population admixture estimator.",
        maturityNoteTr: "Canlı 55-SNP AIM kıtasal sentroid projeksiyonu & popülasyon karışım oranı kestirimi.",
        pillarId: "phenotyping",
        method: "Kidd 55-SNP Continental Centroid GIS Projection",
        methodTr: "Kidd 55-SNP Kıtasal Sentroid GIS Projeksiyonu",
        standard: "ISFG ForenSeq BGA",
        standardTr: "ISFG ForenSeq BGA Standartları",
      },
      {
        id: "craniofacial",
        label: "13. Facial & Craniofacial 3D",
        labelTr: "13. Yüz ve Kraniyofasiyal 3D",
        shortTitle: "3D Craniofacial",
        shortTitleTr: "3D Kraniyofasiyal",
        icon: Brain,
        badge: "CRANIO-3D",
        maturity: "DEMO",
        maturityNote: "Interactive 3D facial morphology phenotype reconstruction simulator.",
        maturityNoteTr: "Etkileşimli 3D yüz morfolojisi fenotip rekonstrüksiyon simülatörü.",
        pillarId: "phenotyping",
        method: "Claes Craniofacial Mesh Morphometry Predictor",
        methodTr: "Claes Kraniyofasiyal Mesh Morfometri Tahmincisi",
        standard: "3D Anthropometric Norms",
        standardTr: "3D Antropometrik Normlar",
      },
      {
        id: "hair",
        label: "14. Hair Texture & Balding",
        labelTr: "14. Saç Dokusu & Kellik Tahmini",
        shortTitle: "Hair & Balding",
        shortTitleTr: "Saç & Kellik",
        icon: Sparkles,
        badge: "HAIR-TEX",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for hair fiber morphology and androgenetic alopecia mapping.",
        maturityNoteTr: "Saç teli morfolojisi ve androjenetik alopesi eşlemesi için araştırma prototipi.",
        pillarId: "phenotyping",
        method: "Polygenic Risk Score (PRS) Follicle Regression",
        methodTr: "Poligenik Risk Skoru (PRS) Folikül Regresyonu",
        standard: "VISAGE EVC Panel",
        standardTr: "VISAGE EVC Paneli",
      },
      {
        id: "freckling",
        label: "15. Freckling & UV Sensitivity",
        labelTr: "15. Çillenme & UV Duyarlılığı",
        shortTitle: "MC1R Epistasis",
        shortTitleTr: "MC1R Epistazı",
        icon: Eye,
        badge: "MC1R-UV",
        maturity: "PLACEHOLDER",
        maturityNote: "Research prototype for MC1R epistatic variant UV sensitivity modeling.",
        maturityNoteTr: "MC1R epistatik varyant UV duyarlılığı modellemesi için araştırma prototipi.",
        pillarId: "phenotyping",
        method: "MC1R Epistatic Variant Loss-of-Function Modifier",
        methodTr: "MC1R Epistatik Varyant Fonksiyon Kaybı Düzenleyicisi",
        standard: "Epistatic Penetrance Scale",
        standardTr: "Epistatik Penetrans Ölçeği",
      },
    ],
  },
  {
    id: "epigenetics",
    label: "Epigenetics & Aging",
    labelTr: "Epigenetik & Yaş Tayini",
    shortLabel: "Epigenetics & Age",
    shortLabelTr: "Epigenetik & Yaş",
    pillarNumber: 4,
    icon: Clock,
    color: "rose",
    tagline: "DNA Methylation Chronometers, tDMR Tissue Deconvolution & Lifestyle Biomarkers",
    taglineTr: "DNA Metilasyon Kronometreleri, tDMR Doku Dekonvolüsyonu & Yaşam Tarzı Biyobelirteçleri",
    description:
      "Horvath & VISAGE multi-tissue elastic net epigenetic age clocks (y0=20.0), tDMR 6-tissue source origin deconvolution (QDA/NNLS), lifestyle AHRR pack-years, and telomere length decay.",
    descriptionTr:
      "Horvath & VISAGE çok dokulu elastik net epigenetik yaş saatleri (y0=20.0), tDMR 6-doku kaynak köken dekonvolüsyonu (QDA/NNLS), yaşam tarzı AHRR paket-yıl ve telomer uzunluk bozunması.",
    researchFile: "pillar_4_epigenetics_aging_research.md",
    tabs: [
      {
        id: "age",
        label: "16. Horvath Epigenetic Clock",
        labelTr: "16. Horvath Epigenetik Yaş Saati",
        shortTitle: "Horvath Clock",
        shortTitleTr: "Horvath Saati",
        icon: Clock,
        badge: "HORVATH",
        maturity: "ACTIVE",
        maturityNote: "Live Horvath 5-CpG methylation age estimation engine with live delta.",
        maturityNoteTr: "Canlı doku deltası ile Horvath 5-CpG metilasyon yaşı kestirim motoru.",
        pillarId: "epigenetics",
        method: "Piecewise Elastic Net Anti-Logit Transformation (y0=20.0)",
        methodTr: "Parçalı Elastik Net Anti-Logit Dönüşümü (y0=20.0)",
        standard: "Horvath (2013) / VISAGE Age",
        standardTr: "Horvath (2013) / VISAGE Yaş Modeli",
      },
      {
        id: "bodyfluid",
        label: "17. Body Fluid tDMR Origin",
        labelTr: "17. Vücut Sıvısı tDMR Kökeni",
        shortTitle: "tDMR Body Fluid",
        shortTitleTr: "tDMR Vücut Sıvısı",
        icon: Syringe,
        badge: "tDMR-FLUID",
        maturity: "DEMO",
        maturityNote: "Tissue-specific differential methylation body fluid classification simulator.",
        maturityNoteTr: "Dokuya özgü diferansiyel metilasyon vücut sıvısı sınıflandırma simülatörü.",
        pillarId: "epigenetics",
        method: "Non-Negative Least Squares (NNLS) / QDA 6-Tissue Deconv",
        methodTr: "Negatif Olmayan En Küçük Kareler (NNLS) / QDA 6-Doku Dekonvolüsyonu",
        standard: "VISAGE Body Fluid Matrix",
        standardTr: "VISAGE Vücut Sıvısı Matrisi",
      },
      {
        id: "lifestyle",
        label: "18. Lifestyle Epigenetics AHRR",
        labelTr: "18. Yaşam Tarzı Epigenetiği AHRR",
        shortTitle: "Lifestyle AHRR",
        shortTitleTr: "Yaşam Tarzı AHRR",
        icon: Zap,
        badge: "AHRR",
        maturity: "DEMO",
        maturityNote: "AHRR environmental smoking & lifestyle epigenetic biomarker analyzer.",
        maturityNoteTr: "AHRR çevresel sigara tüketimi ve yaşam tarzı epigenetik biyobelirteç analizörü.",
        pillarId: "epigenetics",
        method: "AHRR cg05575921 Hypomethylation Pack-Years Regression",
        methodTr: "AHRR cg05575921 Hipometilasyon Paket-Yıl Regresyonu",
        standard: "Lifestyle Epigenetics Norm",
        standardTr: "Yaşam Tarzı Epigenetik Normu",
      },
      {
        id: "telomere",
        label: "19. Telomere Chronometer",
        labelTr: "19. Telomer Biyolojik Kronometresi",
        shortTitle: "Telomere Decay",
        shortTitleTr: "Telomer Bozunması",
        icon: Clock,
        badge: "TELO-CHRONO",
        maturity: "DEMO",
        maturityNote: "Telomere length biological chronometer decay simulator.",
        maturityNoteTr: "Telomer uzunluğu biyolojik kronometre bozunma simülatörü.",
        pillarId: "epigenetics",
        method: "qPCR T/S Ratio Log-Linear Decay Chronometer",
        methodTr: "qPCR T/S Oranı Log-Lineer Bozunma Kronometresi",
        standard: "Telomeric Biological Aging",
        standardTr: "Telomerik Biyolojik Yaşlanma",
      },
      {
        id: "microbiome",
        label: "20. Forensic Microbiome & Metagenomics",
        labelTr: "20. Adli Mikrobiyom & Metagenomik Zekası",
        shortTitle: "Microbiome PMI & LR",
        shortTitleTr: "Mikrobiyom PMI & LR",
        icon: Bug,
        badge: "MICROBIOME",
        maturity: "ACTIVE",
        maturityNote: "Live 16S V4 thanatomicrobiome PMI regression, hidSkinPlex+ touch LR & body fluid deconvolution.",
        maturityNoteTr: "Canlı 16S V4 tanatomikrobiyom PMI regresyonu, hidSkinPlex+ dokunma LR & vücut sıvısı dekonvolüsyonu.",
        pillarId: "epigenetics",
        method: "CoDa CLR Transformation & Random Forest ADD Thermal Summation",
        methodTr: "CoDa CLR Dönüşümü & Random Forest ADD Termal Toplamı",
        standard: "ISO 17025 • ISFG 2024",
        standardTr: "ISO 17025 • ISFG 2024",
      },
    ],
  },
  {
    id: "pathology",
    label: "Physical Evidence & Trace",
    labelTr: "Fiziksel Delil & İz Delil",
    shortLabel: "Physical Trace",
    shortLabelTr: "Fiziksel İz",
    pillarNumber: 5,
    icon: Microscope,
    color: "orange",
    tagline: "3D BPA Least-Squares, SEM-EDX GSR Ballistics, Thermal PMI & Toxicokinetics",
    taglineTr: "3D BPA En Küçük Kareler, SEM-EDX GSR Balistik, Termal PMI & Toksikokinetik",
    description:
      "3D Bloodstain Pattern Analysis (BPA) trigonometric area of origin optimization, ASTM E1588 SEM-EDX GSR ternary classifier, Calliphoridae thermal summation (ADD/ADH), and post-mortem PMR toxicokinetics.",
    descriptionTr:
      "3D Kan Lekesi Örüntü Analizi (BPA) trigonometrik orijin alanı optimizasyonu, ASTM E1588 SEM-EDX GSR üçlü sınıflandırıcısı, Calliphoridae termal toplamı (ADD/ADH) ve ölüm sonrası PMR toksikokinetiği.",
    researchFile: "pillar_5_physical_evidence_research.md",
    tabs: [
      {
        id: "bpa",
        label: "21. Bloodstain Pattern (BPA 3D)",
        labelTr: "21. Kan Lekesi Örüntüsü (BPA 3D)",
        shortTitle: "3D BPA Origin",
        shortTitleTr: "3D BPA Orijini",
        icon: Eye,
        badge: "BPA-3D",
        maturity: "ACTIVE",
        maturityNote: "Live 3D trigonometric area of origin & impact angle calculator.",
        maturityNoteTr: "Canlı 3D trigonometrik orijin alanı ve vuruş açısı hesaplayıcısı.",
        pillarId: "pathology",
        method: "3D Directional Ray Intersection & Least-Squares Origin",
        methodTr: "3D Yönlü Işın Kesişimi & En Küçük Kareler Orijin Alanı",
        standard: "MacDonell (1979) / ASB Standard 033",
        standardTr: "MacDonell (1979) / ASB Standart 033",
      },
      {
        id: "microscopy",
        label: "22. Ballistics & SEM-EDX GSR",
        labelTr: "22. Balistik & SEM-EDX GSR",
        shortTitle: "SEM-EDX & Ballistics",
        shortTitleTr: "SEM-EDX & Balistik",
        icon: Target,
        badge: "GSR-CMC",
        maturity: "ACTIVE",
        maturityNote: "Live ASTM E1588-20 SEM-EDX GSR analysis & 3D CMC firearm striation matching.",
        maturityNoteTr: "Canlı ASTM E1588-20 SEM-EDX GSR atış artığı analizi & 3D CMC namlu izi eşleştirmesi.",
        pillarId: "pathology",
        method: "Pb-Ba-Sb Ternary Characteristic Particle Classifier",
        methodTr: "Pb-Ba-Sb Üçlü Karakteristik Parçacık Sınıflandırıcısı",
        standard: "ASTM E1588-20 / NIST CMC",
        standardTr: "ASTM E1588-20 / NIST CMC Standartları",
      },
      {
        id: "botany",
        label: "23. Forensic Entomology & PMI",
        labelTr: "23. Adli Entomoloji & PMI",
        shortTitle: "Entomology (ADD/ADH)",
        shortTitleTr: "Entomoloji (ADD/ADH)",
        icon: Bug,
        badge: "ENTO-PMI",
        maturity: "ACTIVE",
        maturityNote: "Live Calliphoridae thermal summation (ADD/ADH) & minimum PMI solver.",
        maturityNoteTr: "Canlı Calliphoridae termal toplamı (ADD/ADH) & minimum PMI ölüm zamanı çözücüsü.",
        pillarId: "pathology",
        method: "Thermal Summation K = y * (T - T0) ADD/ADH Integration",
        methodTr: "Termal Toplam K = y * (T - T0) ADD/ADH Entegrasyonu",
        standard: "European Association for Forensic Entomology",
        standardTr: "Avrupa Adli Entomoloji Derneği (EAFE)",
      },
      {
        id: "toxicology",
        label: "24. Trace Spectroscopy & MSI",
        labelTr: "24. İz Spektroskopisi & MSI",
        shortTitle: "MSI & ATR-FTIR",
        shortTitleTr: "MSI & ATR-FTIR",
        icon: Sparkles,
        badge: "MSI-FTIR",
        maturity: "ACTIVE",
        maturityNote: "Live multispectral imaging (365-850nm) & ATR-FTIR / Raman Hit Quality Index matching.",
        maturityNoteTr: "Canlı çok spektrumlu görüntüleme (365-850nm) & ATR-FTIR / Raman Eşleşme Kalite İndeksi (HQI).",
        pillarId: "pathology",
        method: "Vector Euclidean Dot Product Hit Quality Index (HQI)",
        methodTr: "Vektörel Öklid Nokta Çarpımı Eşleşme Kalite İndeksi (HQI)",
        standard: "ASTM E2224 / SWGMAT",
        standardTr: "ASTM E2224 / SWGMAT Standartları",
      },
      {
        id: "serology",
        label: "25. Post-Mortem Toxicokinetics",
        labelTr: "25. Ölüm Sonrası Toksikokinetik",
        shortTitle: "PMR Toxicokinetics",
        shortTitleTr: "PMR Toksikokinetiği",
        icon: Pill,
        badge: "TOX-PMR",
        maturity: "ACTIVE",
        maturityNote: "Live post-mortem drug redistribution (PMR C/P ratios) & Widmark back-extrapolation.",
        maturityNoteTr: "Canlı ölüm sonrası ilaç yeniden dağılımı (PMR C/P oranları) & Widmark geriye dönük hesaplama.",
        pillarId: "pathology",
        method: "Central/Peripheral (C/P) Ratio & Widmark Back-Extrapolation",
        methodTr: "Santral/Periferik (C/P) Oranı & Widmark Geriye Doğru Ekstrapolasyon",
        standard: "SOFT / AAFS Toxicokinetics",
        standardTr: "SOFT / AAFS Toksikokinetik Kılavuzları",
      },
    ],
  },
  {
    id: "lims_governance",
    label: "Governance, LIMS & ZKP",
    labelTr: "Yönetişim, LIMS & ZKP",
    shortLabel: "Governance & ZKP",
    shortLabelTr: "Yönetişim & ZKP",
    pillarNumber: 6,
    icon: ShieldCheck,
    color: "blue",
    tagline: "Cryptographic Binary Merkle Trees, Circom BN254 ZKP & ISO 17025 Uncertainty",
    taglineTr: "Kriptografik İkili Merkle Ağaçları, Circom BN254 ZKP & ISO 17025 Belirsizlik",
    description:
      "Binary Merkle tree chain of custody with O(log2 N) inclusion proofs, Circom Groth16 blind forensic auditor on BN254 pairings, ISO/IEC 17025:2017 GUM expanded uncertainty, and ENFSI 7-tier verbal scale.",
    descriptionTr:
      "O(log2 N) dahil olma kanıtlı ikili Merkle ağacı delil zinciri, BN254 eşleşmeli Circom Groth16 kör adli denetçi, ISO/IEC 17025:2017 GUM genişletilmiş belirsizlik ve ENFSI 7 aşamalı sözel ölçek.",
    researchFile: "pillar_6_lims_zkp_reporting_research.md",
    tabs: [
      {
        id: "lims",
        label: "26. Merkle Custody Ledger",
        labelTr: "26. Merkle Delil Defteri",
        shortTitle: "Merkle Custody",
        shortTitleTr: "Merkle Delil Defteri",
        icon: PackageCheck,
        badge: "MERKLE-COC",
        maturity: "ACTIVE",
        maturityNote: "Live cryptographic binary Merkle tree chain of custody & O(log2 N) proof generator.",
        maturityNoteTr: "Canlı kriptografik ikili Merkle ağacı gözetim zinciri & O(log2 N) kanıt üreteci.",
        pillarId: "lims_governance",
        method: "Binary Merkle Tree O(log2 N) Leaf Inclusion Proofs",
        methodTr: "İkili Merkle Ağacı O(log2 N) Yaprak Dahiliyet Kanıtları",
        standard: "ISO/IEC 17025 §7.8.2 / NIST SP 800-147",
        standardTr: "ISO/IEC 17025 Madde 7.8.2 / NIST SP 800-147",
      },
      {
        id: "zkp",
        label: "27. ZKP Blind Forensic Auditor",
        labelTr: "27. ZKP Kör Adli Denetçi",
        shortTitle: "Circom ZKP Auditor",
        shortTitleTr: "Circom ZKP Denetçisi",
        icon: Lock,
        badge: "ZKP-BN254",
        maturity: "ACTIVE",
        maturityNote: "Live Circom BN254 Groth16 zero-knowledge proof generation & bilinear multi-pairing verification.",
        maturityNoteTr: "Canlı Circom BN254 Groth16 sıfır bilgi ispatı üretimi & çift doğrusal çoklu eşleşme doğrulaması.",
        pillarId: "lims_governance",
        method: "Groth16 Zero-Knowledge SNARK Witness Verification",
        methodTr: "Groth16 Sıfır Bilgi SNARK Tanık Doğrulaması",
        standard: "Circom 2.1 / BN254 Curve",
        standardTr: "Circom 2.1 / BN254 Eğrisi",
      },
      {
        id: "qc",
        label: "28. ISO 17025 QA/QC Matrix",
        labelTr: "28. ISO 17025 KG/KK Matrisi",
        shortTitle: "ISO QA/QC Matrix",
        shortTitleTr: "ISO KG/KK Matrisi",
        icon: ShieldCheck,
        badge: "ISO-17025",
        maturity: "ACTIVE",
        maturityNote: "Live ISO 17025 validation checklist & standard operating procedure validator.",
        maturityNoteTr: "Canlı ISO 17025 doğrulama kontrol listesi & standart çalışma prosedürü denetçisi.",
        pillarId: "lims_governance",
        method: "GUM Expanded Uncertainty U95% = 2.00 * u_c",
        methodTr: "GUM Genişletilmiş Belirsizlik U95% = 2.00 * u_c",
        standard: "ISO/IEC 17025:2017 / GUM JCGM 100",
        standardTr: "ISO/IEC 17025:2017 / GUM JCGM 100",
      },
      {
        id: "court",
        label: "29. Expert Witness Court Mode",
        labelTr: "29. Bilirkişi Mahkeme Modu",
        shortTitle: "Expert Court Mode",
        shortTitleTr: "Bilirkişi Mahkeme Modu",
        icon: Scale,
        badge: "COURT-MODE",
        maturity: "DEMO",
        maturityNote: "Interactive expert witness courtroom reporting & ENFSI verbal predicate synthesizer.",
        maturityNoteTr: "Etkileşimli bilirkişi duruşma raporlaması & ENFSI sözel ifade sentezleyicisi.",
        pillarId: "lims_governance",
        method: "ENFSI (2017) 7-Tier Standardized Verbal Predicates",
        methodTr: "ENFSI (2017) 7 Aşamalı Standartlaştırılmış Sözel İfadeler",
        standard: "ENFSI Guideline / Daubert Standard",
        standardTr: "ENFSI Kılavuzu / Daubert Standardı",
      },
      {
        id: "evidenceos",
        label: "30. 3D Spatial Juror Visualizer",
        labelTr: "30. 3D Uzamsal Jüri Görselleştirici",
        shortTitle: "3D Juror Visualizer",
        shortTitleTr: "3D Jüri Görselleştirici",
        icon: Layers,
        badge: "JUROR-3D",
        maturity: "DEMO",
        maturityNote: "3D spatial crime scene reconstruction & interactive juror visualizer engine.",
        maturityNoteTr: "3D uzamsal olay yeri rekonstrüksiyonu & etkileşimli jüri görselleştirme motoru.",
        pillarId: "lims_governance",
        method: "Spatial 3D Photogrammetry & Trajectory Overlay",
        methodTr: "Uzamsal 3D Fotogrametri & Yörünge Katmanı",
        standard: "Courtroom Demonstrative Evidence",
        standardTr: "Mahkeme Gösterimsel Delil Standardı",
      },
    ],
  },
  {
    id: "geoint",
    label: "Geo-Forensic Intelligence",
    labelTr: "Jeo-Forensik İstihbarat",
    shortLabel: "Geo-Intelligence",
    shortLabelTr: "Jeo-İstihbarat",
    pillarNumber: 7,
    icon: Globe,
    color: "teal",
    tagline: "Multi-Isotope Isoscapes, Forensic Pedology CoDa & Rossmo Spatial Profiling",
    taglineTr: "Çoklu İzotop İzomapları, Adli Toprak Pedolojisi CoDa & Rossmo Mekânsal Profilleme",
    description:
      "Multi-isotope H/O/Sr spatial isoscapes, QXRD Rietveld soil pedology compositional data analysis (CoDa), palynology Relative Pollen Frequency (RPF), and Rossmo geographic hunting surfaces.",
    descriptionTr:
      "Çoklu izotop H/O/Sr mekânsal izomapları, QXRD Rietveld toprak kompozisyonel veri analizi (CoDa), palinoloji Bağıl Polen Frekansı (RPF) ve Rossmo coğrafi avlanma yüzeyleri.",
    researchFile: "pillar_7_geo_forensics_research.md",
    tabs: [
      {
        id: "geo_isoscape",
        label: "31. Multi-Isotope Isoscape Engine",
        labelTr: "31. Çoklu İzotop İzomap Motoru",
        shortTitle: "Isoscape Isotope",
        shortTitleTr: "İzotop İzomap",
        icon: Globe,
        badge: "ISOTOPE",
        maturity: "ACTIVE",
        maturityNote: "Live multi-isotope spatial isoscape mapping (H/O/Sr) & Bayesian centroid resolution.",
        maturityNoteTr: "Canlı çoklu izotop mekânsal haritalama (H/O/Sr) & Bayesyen sentroid çözünürlüğü.",
        pillarId: "geoint",
        method: "Spatial Multi-Isotope Bayesian Surface Likelihood Integration",
        methodTr: "Mekânsal Çoklu İzotop Bayesyen Yüzey Olabilirlik Entegrasyonu",
        standard: "IAEA GNIP / Bowen Isoscape",
        standardTr: "IAEA GNIP / Bowen İzotop Haritası",
      },
      {
        id: "geo_soil",
        label: "32. Forensic Soil Pedology & CoDa",
        labelTr: "32. Adli Toprak Pedolojisi & CoDa",
        shortTitle: "Soil Pedology CoDa",
        shortTitleTr: "Toprak Pedolojisi CoDa",
        icon: Mountain,
        badge: "SOIL-CODA",
        maturity: "ACTIVE",
        maturityNote: "Live QXRD Rietveld mineralogy, ZTR index & ASTM E3272-21 Hotelling T2 comparison.",
        maturityNoteTr: "Canlı QXRD Rietveld mineralojisi, ZTR indeksi & ASTM E3272-21 Hotelling T2 karşılaştırması.",
        pillarId: "geoint",
        method: "Centered Log-Ratio (clr) & Hotelling T2 Multivariate Distance",
        methodTr: "Merkezli Log-Oran (clr) & Hotelling T2 Çok Değişkenli Mesafesi",
        standard: "ASTM E3272-21 Forensic Soil",
        standardTr: "ASTM E3272-21 Adli Toprak Standartları",
      },
      {
        id: "geo_palynology",
        label: "33. Palynology & eDNA Metagenomics",
        labelTr: "33. Palinoloji & eDNA Metagenomik",
        shortTitle: "Palynology & eDNA",
        shortTitleTr: "Palinoloji & eDNA",
        icon: TreePine,
        badge: "PALYNO",
        maturity: "ACTIVE",
        maturityNote: "Live Relative Pollen Frequency (RPF), 6-biome classifier & 16S/ITS spatial regression.",
        maturityNoteTr: "Canlı Bağıl Polen Frekansı (RPF), 6-biyom sınıflandırıcı & 16S/ITS uzamsal regresyonu.",
        pillarId: "geoint",
        method: "Relative Pollen Frequency (RPF) & 16S/ITS OTU Regression",
        methodTr: "Bağıl Polen Frekansı (RPF) & 16S/ITS OTU Regresyonu",
        standard: "Forensic Palynology Protocols",
        standardTr: "Adli Palinoloji Protokolleri",
      },
      {
        id: "geo_rossmo",
        label: "34. Rossmo Geographic Profiling",
        labelTr: "34. Rossmo Coğrafi Profilleme",
        shortTitle: "Rossmo Profiling",
        shortTitleTr: "Rossmo Profilleme",
        icon: CrosshairIcon,
        badge: "ROSSMO",
        maturity: "ACTIVE",
        maturityNote: "Live Rossmo targeted hunting probability surface & Canter circle Marauder classification.",
        maturityNoteTr: "Canlı Rossmo hedeflenmiş avlanma olasılık yüzeyi & Canter çemberi Yağmacı (Marauder) sınıflandırması.",
        pillarId: "geoint",
        method: "Rossmo Distance-Decayed Targeted Hunting Probability Surface",
        methodTr: "Rossmo Mesafe Azalımlı Hedeflenmiş Avlanma Olasılık Yüzeyi",
        standard: "Rossmo Formula / ECRI Standards",
        standardTr: "Rossmo Formülü / ECRI Standartları",
      },
      {
        id: "geo_fusion",
        label: "35. Multi-Criteria Bayesian GIS Fusion",
        labelTr: "35. Çok Kriterli Bayesyen GIS Füzyonu",
        shortTitle: "Bayesian GIS Fusion",
        shortTitleTr: "Bayesyen GIS Füzyonu",
        icon: Layers,
        badge: "FUSION",
        maturity: "ACTIVE",
        maturityNote: "Live multi-criteria Bayesian raster integration, 2D adaptive KDE & ENFSI report generator.",
        maturityNoteTr: "Canlı çok kriterli Bayesyen raster entegrasyonu, 2D adaptif KDE & ENFSI rapor üreteci.",
        pillarId: "geoint",
        method: "Spatial Log-Likelihood Raster Product Fusion & 2D Adaptive KDE",
        methodTr: "Mekânsal Log-Olabilirlik Raster Ürün Füzyonu & 2D Adaptif KDE",
        standard: "ENFSI Spatial Guideline",
        standardTr: "ENFSI Mekânsal Analiz Kılavuzu",
      },
    ],
  },
];

export const ALL_SUBSYSTEM_TABS: SubsystemTab[] = SUBSYSTEM_CATEGORIES.flatMap((c) => c.tabs);

export function getSubsystemCategories(lang: "en" | "tr" = "en"): SubsystemCategory[] {
  if (lang !== "tr") return SUBSYSTEM_CATEGORIES;
  return SUBSYSTEM_CATEGORIES.map((cat) => ({
    ...cat,
    label: cat.labelTr || cat.label,
    shortLabel: cat.shortLabelTr || cat.shortLabel,
    tagline: cat.taglineTr || cat.tagline,
    description: cat.descriptionTr || cat.description,
    tabs: cat.tabs.map((tab) => ({
      ...tab,
      label: tab.labelTr || tab.label,
      shortTitle: tab.shortTitleTr || tab.shortTitle,
      maturityNote: tab.maturityNoteTr || tab.maturityNote,
      method: tab.methodTr || tab.method,
      standard: tab.standardTr || tab.standard,
    })),
  }));
}

export function getSubsystemCategory(
  id: CategoryId | string,
  lang: "en" | "tr" = "en"
): SubsystemCategory | undefined {
  const cats = getSubsystemCategories(lang);
  return cats.find((c) => c.id === id);
}

export function getSubsystemTab(
  id: string,
  lang: "en" | "tr" = "en"
): SubsystemTab | undefined {
  const cats = getSubsystemCategories(lang);
  const allTabs = cats.flatMap((c) => c.tabs);
  return allTabs.find((t) => t.id === id);
}

export function getMaturityConfig(lang: "en" | "tr" = "en") {
  if (lang !== "tr") return MATURITY_CONFIG;
  return {
    ACTIVE: {
      ...MATURITY_CONFIG.ACTIVE,
      label: "AKTİF MOTOR",
      shortLabel: "AKTİF",
      desc: "Doğrulanmış matematiksel motor, canlı biyobilişimsel parametreler ve ISO uyumlu algoritmalar.",
    },
    DEMO: {
      ...MATURITY_CONFIG.DEMO,
      label: "DEMO SİMÜLATÖR",
      shortLabel: "DEMO",
      desc: "Etkileşimli bilimsel simülasyon ve kalibre edilmiş eğitim benchmark modeli.",
    },
    PLACEHOLDER: {
      ...MATURITY_CONFIG.PLACEHOLDER,
      label: "ARAŞTIRMA PROTOTİPİ",
      shortLabel: "PROTOTİP",
      desc: "Aktif geliştirme ve araştırma yol haritası altındaki deneysel laboratuvar modülü.",
    },
  };
}
