"""
Unit Tests for Multi-Vendor FGG Genotype Parsers.
"""

import pytest
from backend.node.services.forensic.genomics.fgg.schemas import PlatformFormatEnum, GenotypeStateEnum
from backend.node.services.forensic.genomics.fgg.parser import FGGGenotypeParser


class TestFGGGenotypeParser:
    """Tests multi-platform file detection and parsing."""

    def test_parse_23andme_tsv(self):
        content = (
            "# This data file generated by 23andMe at: Tue Aug 20 2026\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs12345\t1\t1000\tAA\n"
            "rs67890\t1\t2000\tCT\n"
            "rs11111\t2\t3000\t--\n"
            "rs22222\tX\t4000\tG\n"
        )
        detected = FGGGenotypeParser.detect_format(content)
        assert detected == PlatformFormatEnum.TWENTY_THREE_AND_ME_V5

        profile = FGGGenotypeParser.parse_profile(content, profile_id="TEST_23ANDME")
        assert profile.platform == PlatformFormatEnum.TWENTY_THREE_AND_ME_V5
        assert "1" in profile.chromosome_blocks
        assert "2" in profile.chromosome_blocks
        assert "X" in profile.chromosome_blocks
        assert profile.chromosome_blocks["1"].snp_count == 2
        assert profile.qc_report.total_snps_evaluated == 4
        assert profile.qc_report.called_snps == 3
        assert profile.qc_report.missing_snps == 1

    def test_parse_ancestrydna_tsv(self):
        content = (
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs1001\t1\t50000\tA\tA\n"
            "rs1002\t1\t60000\tC\tT\n"
            "rs1003\t22\t70000\tG\tG\n"
        )
        detected = FGGGenotypeParser.detect_format(content)
        assert detected == PlatformFormatEnum.ANCESTRY_DNA

        profile = FGGGenotypeParser.parse_profile(content, profile_id="TEST_ANCESTRY")
        assert profile.platform == PlatformFormatEnum.ANCESTRY_DNA
        assert profile.qc_report.total_snps_evaluated == 3
        assert profile.qc_report.called_snps == 3
        assert profile.qc_report.call_rate_percentage == 100.0

    def test_parse_ftdna_csv(self):
        content = (
            "RSID,CHROMOSOME,POSITION,RESULT\n"
            '"rs5001","1","123456","AA"\n'
            '"rs5002","1","123457","CT"\n'
            '"rs5003","1","123458","--"\n'
        )
        detected = FGGGenotypeParser.detect_format(content)
        assert detected == PlatformFormatEnum.FAMILY_TREE_DNA_CSV

        profile = FGGGenotypeParser.parse_profile(content, profile_id="TEST_FTDNA")
        assert profile.platform == PlatformFormatEnum.FAMILY_TREE_DNA_CSV
        assert profile.qc_report.total_snps_evaluated == 3
        assert profile.qc_report.called_snps == 2
        assert profile.qc_report.missing_snps == 1

    def test_parse_vcf_wgs(self):
        content = (
            "##fileformat=VCFv4.2\n"
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tNA12878\n"
            "chr1\t1000\trs101\tA\tG\t.\tPASS\t.\tGT\t0/0\n"
            "chr1\t2000\trs102\tC\tT\t.\tPASS\t.\tGT\t0/1\n"
            "chr1\t3000\trs103\tG\tA\t.\tPASS\t.\tGT\t1/1\n"
            "chr1\t4000\trs104\tT\tC\t.\tPASS\t.\tGT\t./.\n"
        )
        detected = FGGGenotypeParser.detect_format(content)
        assert detected == PlatformFormatEnum.VCF_WGS_PHASED

        profile = FGGGenotypeParser.parse_profile(content, profile_id="TEST_VCF")
        assert profile.platform == PlatformFormatEnum.VCF_WGS_PHASED
        assert profile.qc_report.total_snps_evaluated == 4
        assert profile.qc_report.called_snps == 3
        assert profile.qc_report.missing_snps == 1
