"""
Unit Tests for Multi-Vendor Genotype Ingestion Parser.
"""

import pytest
from backend.node.services.forensic.genomics.bga.schemas import (
    PlatformFormatEnum,
    AIMPanelTypeEnum,
    GenomicAssemblyEnum
)
from backend.node.services.forensic.genomics.bga.parser import BGAGenotypeParser


def test_23andme_parser():
    """Verify ingestion of 23andMe microarray raw text."""
    raw_23andme = """# This data file generated by 23andMe at: Sun Aug 23 2026
# Below is a list of your genotypes.
# rsid\tchromosome\tposition\tgenotype
rs2814778\t1\t159174683\tCC
rs16891982\t5\t33984570\tCG
rs1426654\t15\t48426484\tAA
rs12913832\t15\t28365618\tGG
"""
    sample = BGAGenotypeParser.parse_raw_text(raw_23andme, sample_id="23ANDME_TEST")
    assert sample.sample_id == "23ANDME_TEST"
    assert sample.detected_platform == PlatformFormatEnum.MICROARRAY_23ANDME
    assert sample.called_loci_count == 4
    assert sample.genotypes["rs2814778"].allele_1 == "C"
    assert sample.genotypes["rs2814778"].allele_2 == "C"
    assert sample.genotypes["rs2814778"].dosage_alt == 2.0
    assert sample.genotypes["rs16891982"].is_heterozygous is True


def test_ancestrydna_parser():
    """Verify ingestion of AncestryDNA raw text."""
    raw_ancestry = """#AncestryDNA raw data download
#rsid\tchromosome\tposition\tallele1\tallele2
rs2814778\t1\t159174683\tT\tC
rs1426654\t15\t48426484\tG\tG
"""
    sample = BGAGenotypeParser.parse_raw_text(raw_ancestry, sample_id="ANCESTRY_TEST")
    assert sample.detected_platform == PlatformFormatEnum.MICROARRAY_ANCESTRYDNA
    assert sample.called_loci_count == 2
    assert sample.genotypes["rs2814778"].is_heterozygous is True
    assert sample.genotypes["rs1426654"].dosage_alt == 2.0


def test_vcf_parser():
    """Verify ingestion of ForenSeq / WGS VCF formatted file."""
    raw_vcf = """##fileformat=VCFv4.2
##reference=GRCh38
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE01
1\t159204893\trs2814778\tT\tC\t99\tPASS\t.\tGT:DP\t0/1:45
15\t48187887\trs1426654\tA\tG\t99\tPASS\t.\tGT:DP\t1/1:60
"""
    sample = BGAGenotypeParser.parse_raw_text(raw_vcf, sample_id="VCF_TEST")
    assert sample.detected_platform in (PlatformFormatEnum.WGS_VCF_4_2, PlatformFormatEnum.FORENSEQ_VCF)
    assert sample.called_loci_count == 2
    assert sample.genotypes["rs2814778"].dosage_alt == 1.0
    assert sample.genotypes["rs1426654"].dosage_alt == 2.0


def test_snapshot_tsv_parser():
    """Verify ingestion of SNaPshot / AmpliSeq tab-separated calls."""
    raw_tsv = """rs2814778\tC\tC
rs16891982\tC\tG
rs1426654\tA\tA
"""
    sample = BGAGenotypeParser.parse_raw_text(raw_tsv, sample_id="SNAPSHOT_TEST")
    assert sample.called_loci_count == 3
    assert sample.genotypes["rs16891982"].is_heterozygous is True
