"""
Integration Tests for Forensic Genetic Genealogy (FGG / IGG) REST API Endpoints.
"""

import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


class TestFGGAPIEndpoints:
    """Tests all FGG / IGG HTTP endpoints."""

    def test_get_benchmarks_endpoint(self):
        resp = client.get("/api/forensic/fgg/benchmarks")
        assert resp.status_code == 200
        data = resp.json()
        assert "benchmarks" in data
        assert len(data["benchmarks"]) == 3

    def test_ingest_genotype_file_endpoint(self):
        content = (
            "# This data file generated by 23andMe at: Tue Aug 20 2026\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1001\t1\t1000\tAA\n"
            "rs1002\t1\t2000\tCT\n"
            "rs1003\t2\t3000\t--\n"
        )
        payload = {
            "raw_text": content,
            "profile_id": "TEST_REST_PROFILE"
        }
        resp = client.post("/api/forensic/fgg/ingest", json=payload)
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "SUCCESS"
        assert data["profile_id"] == "TEST_REST_PROFILE"
        assert "qc_report" in data

    def test_pairwise_ibd_endpoint(self):
        p1 = "rs101\t1\t1000\tAA\nrs102\t1\t2000\tCC\n"
        p2 = "rs101\t1\t1000\tAA\nrs102\t1\t2000\tCT\n"
        payload = {
            "raw_text_a": p1,
            "profile_id_a": "A",
            "raw_text_b": p2,
            "profile_id_b": "B"
        }
        resp = client.post("/api/forensic/fgg/ibd-pairwise", json=payload)
        assert resp.status_code == 200
        data = resp.json()
        assert data["sample_a_id"] == "A"
        assert data["sample_b_id"] == "B"
        assert "total_shared_cm" in data

    def test_validate_legal_endpoint(self):
        payload = {
            "case_id": "CASE_REST_01",
            "jurisdiction": "US_DOJ_INTERIM_2019",
            "offense_type": "HOMICIDE",
            "is_codis_exhausted": True,
            "prosecutor_authorization_id": "DA_REST_88",
            "opt_in_matches_only_enforced": True
        }
        resp = client.post("/api/forensic/fgg/validate-legal", json=payload)
        assert resp.status_code == 200
        data = resp.json()
        assert data["is_compliant"] is True
        assert "INVESTIGATIVE LEADS ONLY" in data["lead_disclaimer_notice"]

    def test_sample_destruction_order_endpoint(self):
        payload = {
            "case_id": "CASE_REST_02",
            "statutory_basis": "Maryland Title 17 §17-104",
            "reference_sample_ids": ["REF_01", "REF_02"],
            "certifying_officer": "Captain Miller"
        }
        resp = client.post("/api/forensic/fgg/sample-destruction-order", json=payload)
        assert resp.status_code == 200
        data = resp.json()
        assert data["is_destruction_verified"] is True
        assert len(data["certificate_hash"]) == 64

    def test_evaluate_benchmark_endpoint(self):
        # Test VECTOR_FGG_01 (CEPH Parent-Child)
        resp1 = client.post("/api/forensic/fgg/evaluate-benchmark", json={"benchmark_id": "VECTOR_FGG_01"})
        assert resp1.status_code == 200
        d1 = resp1.json()
        assert d1["total_shared_cm"] > 1500.0
        assert d1["top_candidate"]["degree"] == "DEGREE_1_PARENT_CHILD"
        assert d1["legal_compliance"]["is_compliant"] is True

        # Test VECTOR_FGG_02 (Ashkenazi Endogamy)
        resp2 = client.post("/api/forensic/fgg/evaluate-benchmark", json={"benchmark_id": "VECTOR_FGG_02"})
        assert resp2.status_code == 200
        d2 = resp2.json()
        assert d2["is_endogamy_suspected"] is True

        # Test VECTOR_FGG_03 (GSK Investigative Case)
        resp3 = client.post("/api/forensic/fgg/evaluate-benchmark", json={"benchmark_id": "VECTOR_FGG_03"})
        assert resp3.status_code == 200
        d3 = resp3.json()
        assert d3["pedigree_tree"] is not None
